name: SilenceCMD
version: 1.1
main: fr.MrJuJu0319.Main
api-version: "1.20"
commands:
  sgive:
    description: "Gives an item to a player secretly"
  seco:
    description: "donne de l'argent en secret"